export const SOURCES = [
  {id:'plos-2024',title:'Ritka kromoszómaeltérések: a NIPT diagnosztikai pontossága',authors:'Kónya és munkatársai',year:2024,type:'Meta-analízis',url:'https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0308008',doi:'10.1371/journal.pone.0308008',access:'Teljes szöveg áttekintve. A mellékletek tételes ellenőrzése és a klinikai jóváhagyás nyitott.',scope:'17 vizsgálat · 740 076 teszt',limitations:'Kis kromoszómaspecifikus esetszámok, heterogenitás és publikációs torzítás. A confirmed és extended külön végpont.',estimates:[{label:'Genetikailag megerősített végpont',value:'7%',interval:'95% CI: 4–11%',proportion:7,ciLow:4,ciHigh:11},{label:'Kiterjesztett végpont',value:'13%',interval:'95% CI: 8–20%',proportion:13,ciLow:8,ciHigh:20}]},
  {id:'ajog-2026',title:'Discordáns NIPT és a terhesség későbbi kimenetelei',authors:'Kónya és munkatársai',year:2026,type:'Meta-analízis',url:'https://pubmed.ncbi.nlm.nih.gov/41297782/',doi:'10.1016/j.ajog.2025.11.029',access:'Absztrakt és kapcsolódó doktori értekezés. Az eredeti teljes szöveg és mellékletek szerzői ellenőrzése nyitott.',scope:'16 vizsgálat · 681 633 terhesség',limitations:'Kromoszómafüggő összefüggések, eltérő kimenetel-definíciók és követés. A csoportadat nem személyes szövődmény-előrejelzés.',estimates:[]},
  {id:'xue-2026',title:'Triszómia 15 és UPD15: két külön diagnosztikai kérdés',authors:'Xue és munkatársai',year:2026,type:'Kohorsz és meta-analízis',url:'https://pubmed.ncbi.nlm.nih.gov/41118657/',doi:'10.1002/uog.70106',access:'Publikált összefoglaló áttekintve. Részletes szakmai ellenőrzés szükséges.',scope:'T15-pozitív egyes terhességek',limitations:'A normális kariotípus nem zárja ki automatikusan az UPD-t. Az eltérő végpontok számai nem adhatók össze.',estimates:[]},
  {id:'liu-2026',title:'A mozaikossági mutató önálló használatának korlátai',authors:'Liu és munkatársai',year:2026,type:'Retrospektív kohorsz',url:'https://pubmed.ncbi.nlm.nih.gov/42631554/',doi:'10.1002/pd.70237',access:'Publikált összefoglaló áttekintve.',scope:'Egycentrumos vizsgálat · platformfüggő TMR',limitations:'Korlátozott önálló előrejelző teljesítmény. A demó nem számít kockázatot TMR, magzati frakció vagy Z-érték alapján.',estimates:[]},
  {id:'smfm-74',title:'SMFM #74: cfDNA-szűrés és az eredmények követése',authors:'SMFM · Rink, Dugoff, Kuller',year:2025,type:'Szakmai ajánlás',url:'https://publications.smfm.org/publications/620-society-for-maternal-fetal-medicine-consult-series-74cell/',doi:'10.1002/pmf2.70139',access:'Ajánlás és PDF áttekintve.',scope:'Kromoszómafüggő diagnosztikai mérlegelés',limitations:'Nem magyar intézményi protokoll. Az alkalmazhatóság és az átfedő kromoszómacsoportok szakmai egyeztetést igényelnek.',estimates:[]},
  {id:'ispd-2023',title:'ISPD: NIPT az egyes terhességekben',authors:'ISPD · Hui és munkatársai',year:2023,type:'Szakmai állásfoglalás',url:'https://obgyn.onlinelibrary.wiley.com/doi/10.1002/pd.6357',doi:'10.1002/pd.6357',access:'Állásfoglalás áttekintve.',scope:'A kiterjesztett szűrés bizonyítékainak korlátai',limitations:'Az app nem bizonyítja a rutinszerű ritkaeltérés-szűrés klinikai hasznát.',estimates:[]},
  {id:'rcog-8',title:'RCOG #8: mintavételi időablakok',authors:'RCOG',year:2021,type:'Szakmai ajánlás',url:'https://www.rcog.org.uk/gtg8',doi:'',access:'2024 decemberében felülvizsgálva és két évvel meghosszabbítva.',scope:'Amniocentézis: nem 15+0 hét előtt',limitations:'Az időablak megnyílása önmagában nem beavatkozási indikáció. A demó időszámítási referenciája.',estimates:[]},
  {id:'hu-002106',title:'Magyar NIPT-irányelv · 002106',authors:'Egészségügyi Szakmai Kollégium',year:2021,type:'Felülvizsgálandó hazai irányelv',url:'https://neak.gov.hu/pfile/file?inline=true&path=/letoltheto/EOSZEF_letoltheto_doku/002106-2021_Az_anyai_verben_keringo_sejtmentes_szabad_magzati_DNS_alapu_non-invaziv_tesztekrol_NIPT_',doi:'',access:'A dokumentum feltüntetett érvényessége 2024. november 15-én lejárt.',scope:'Történeti hazai kontextus',limitations:'Aktuális ellátási szabályként nincs aktiválva. A jelenlegi helyi protokoll szakmai ellenőrzése szükséges.',estimates:[]}
];

export const RULES = {
  version:'0.1.0-demo',engineVersion:'1',approvalStatus:'pending',clinicalApproved:false,
  supportedChromosomes:[7,15,16,22],reviewedOn:'2026-10-03',
  sources:['plos-2024','ajog-2026','xue-2026','liu-2026','smfm-74','ispd-2023','rcog-8'],
  steps:{
    complete_context:{id:'complete_context',title:'Hiányzó leletadatok áttekintése',reason:'Az ismeretlen adat nem jelent negatív eredményt. A betegút következő lépéséhez előbb az adatok pontosítása szükséges.',window:'Adatpontosításkor',sources:['smfm-74']},
    diagnostic_review:{id:'diagnostic_review',title:'A diagnosztikai tisztázás megbeszélése',reason:'A pozitív NIPT szűrési eredmény. A megerősítés módját az orvos a lelet, az ultrahang és a terhességi kor alapján mérlegeli.',window:'Az orvos által meghatározandó',sources:['smfm-74','ispd-2023']},
    specimen_review:{id:'specimen_review',title:'A minta és a vizsgálati lefedettség ellenőrzése',reason:'A beérkezett vizsgálatból a demó nem állapít meg magzati megerősítést. Külön ellenőrzendő a mintatípus, a módszer és a célzott eltérés lefedettsége.',window:'Szakmai felülvizsgálatkor',sources:['smfm-74']},
    upd_review:{id:'upd_review',title:'Az UPD / imprinting kérdésének áttekintése',reason:'A normális kromoszómaszám nem zár ki minden genetikai eltérést. A további vizsgálat szükségességét klinikai genetikus értékeli.',window:'Az orvos által meghatározandó',sources:['smfm-74','xue-2026']},
    followup_review:{id:'followup_review',title:'A további gondozási terv egyeztetése',reason:'Discordáns lelet után külön mérlegelendő a lepényi eredet lehetősége, a még nyitott genetikai kérdés és a gondozás. A követés gyakoriságát ez a demó nem határozza meg.',window:'Egyéni orvosi terv szerint',sources:['ajog-2026','smfm-74']},
    confirmed_finding_review:{id:'confirmed_finding_review',title:'A megerősítő lelet szakorvosi megbeszélése',reason:'A célzott magzatvíz-vizsgálatban eltérés szerepel. Jelentősége, a várható tünetek és a gondozás egyedi szakértői értékelést igényelnek.',window:'Egyéni orvosi terv szerint',sources:['smfm-74']},
    specialist_review:{id:'specialist_review',title:'Szakértői felülvizsgálat szükséges',reason:'Az eset adatai a bemutató hatókörén kívüliek, ellentmondásosak vagy külön szakmai mérlegelést igényelnek.',window:'A kezelőorvossal egyeztetendő',sources:['smfm-74','ispd-2023']}
  }
};

export const CHROMOSOMES = {
  7:{title:'7-es kromoszóma',tag:'Diagnosztikai tisztázás',description:'A szűrés, a magzati megerősítés és a lepényi eredet lehetősége külön kérdés. Az UPD / imprinting jelentőségét külön szakmai mérlegelés kezeli.',sources:['plos-2024','smfm-74']},
  15:{title:'15-ös kromoszóma',tag:'UPD külön kérdés',description:'A kromoszómaszám vizsgálata és az UPD15 tisztázása külön eredmény. A normális kariotípus önmagában nem zárja le mindkét kérdést.',sources:['xue-2026','smfm-74']},
  16:{title:'16-os kromoszóma',tag:'A gondozás követése',description:'A magzati lelet és a terhesség későbbi követése külön ág. A lepényi eredet feltételezése nem azonos annak igazolásával.',sources:['ajog-2026','smfm-74']},
  22:{title:'22-es kromoszóma',tag:'Lelet és ultrahang együtt',description:'A genetikai és ultrahangos eredményeket időben együtt kell áttekinteni. A bemutató egyikből sem számít személyes betegségi valószínűséget.',sources:['plos-2024','ajog-2026','smfm-74']}
};
