import {escapeHtml as e,fullDate,icon} from './ui.js';
import {gestation,weekLabel} from './engine.js';
import {dashboardMetrics,cohortCard,heroArtwork} from './visuals.js';

export function overviewPanel(state,{allCases=false,filter='all',badge}){
  const m=dashboardMetrics(state);
  const cases=state.cases.filter(c=>filter==='all'||(filter==='active'?c.outcome==='ongoing':c.outcome!=='ongoing'));
  return `<div class="page-heading"><div><div class="eyebrow">Orvosi munkaterület</div><h1>${allCases?'Bemutatóesetek':'Esetáttekintés'}</h1><p>A lényeg egy pillantásra. A részletek, amikor szükséged van rájuk.</p><a class="overview-guide-link" href="./utmutato.html" target="_blank" rel="noopener noreferrer">${icon('book')} Használati útmutató <span aria-hidden="true">↗</span></a></div><button class="button primary" data-action="new-case">${icon('plus')} Új mintaeset</button></div>
  ${allCases?'':`<section class="overview-hero"><div class="hero-copy"><span class="hero-kicker"><span></span> NIPT BETEGÚT · 0.2</span><h2>Egy lelet.<br><em>Érthető következő lépések.</em></h2><p>A genetikai jelzéstől a megbeszélt tervig.<br>Összekapcsolt orvosi és páciensnézet.</p><div class="hero-actions"><a class="button primary" href="#case/demo-15">Betegút megnyitása ${icon('chevron')}</a><button class="button light" data-action="patient-preview">${icon('heart')} Páciensnézet</button></div><div class="hero-tags"><span>T7</span><span>T15</span><span>T16</span><span>T22</span><small>Négy kiemelt betegút</small></div></div><div class="hero-art-wrap">${heroArtwork('doctor')}<span class="art-note">A tisztázás minden esetben közös szakmai döntés.</span></div></section>`}
  <div class="stats v02-stats">${[
    ['case',m.active,'Folyamatban lévő eset','A bemutató aktív esetei','blue'],
    ['share',m.shared,'Páciensnek megosztva','Aktuális, egyeztetett terv','teal'],
    ['clock',m.review,'Áttekintésre vár','Új terv vagy felülvizsgálat','amber']
  ].map(([symbol,n,label,note,tone])=>`<div class="stat stat-${tone}"><div class="stat-top"><span class="stat-icon">${icon(symbol)}</span><small>MINTAADATOK</small></div><div class="stat-number">${n}</div><strong class="stat-title">${label}</strong><span class="stat-description">${note}</span></div>`).join('')}</div>
  <div class="dashboard-grid"><section class="card"><div class="card-header"><div><h2>${allCases?'Minden eset':'Figyelem a következő lépésen'}</h2><small>${state.cases.length} mintaeset · közös munkafolyamat</small></div><span class="table-symbol">${icon('case')}</span></div><div class="filters" aria-label="Esetszűrő">${[['all','Mind'],['active','Folyamatban'],['closed','Lezárt']].map(([id,label])=>`<button class="filter ${filter===id?'active':''}" aria-pressed="${filter===id}" data-filter="${id}">${label}</button>`).join('')}</div><div class="table-wrap"><table class="case-table"><thead><tr><th>Eset</th><th>NIPT-jelzés</th><th>Terhességi kor</th><th>Állapot</th><th><span class="sr-only">Megnyitás</span></th></tr></thead><tbody>${cases.map(c=>`<tr><td><a class="case-link" href="#case/${e(c.id)}">${e(c.label)}</a><span class="case-code mono">${e(c.code)}</span></td><td><span class="chromosome c${c.chromosome}">T${c.chromosome}</span></td><td><span class="nowrap">${weekLabel(gestation(c,c.outcome==='ongoing'?state.demoDate:c.closedOn||state.demoDate))} hét</span></td><td>${badge(c)}</td><td><a class="button small row-open" href="#case/${e(c.id)}" aria-label="${e(c.label)} megnyitása">${icon('chevron')}<span class="sr-only">Megnyitás</span></a></td></tr>`).join('')||'<tr><td colspan="5">Ebben a csoportban nincs eset.</td></tr>'}</tbody></table></div><div class="card-foot">${icon('calendar')} Bemutató dátuma: ${fullDate(state.demoDate)} <button class="button subtle small" data-action="demo-date">Módosítás</button></div></section>
  <aside class="side-stack">${cohortCard(state)}<section class="research-mini"><span class="eyebrow">Bizonyíték, kontextusban</span><div class="research-head"><span class="research-icon">${icon('book')}</span><h2>A számok mögött<br>kutatások állnak.</h2></div><div class="research-figures"><div><strong>17</strong><span>vizsgálat</span></div><div><strong>740 076</strong><span>GW-NIPT-teszt</span></div></div><p>A PLOS 2024 meta-analízis vizsgálati populációja. A PPV végpontjai és bizonytalansága a tudástárban.</p><a href="#knowledge" class="button">Ábrák és bizonyítékok ${icon('chevron')}</a></section></aside></div>
  <div class="scope-note">${icon('info')}<span>Mintaadatokkal működő bemutató. T7, T15, T16 és T22 jelzések egyes terhességben; egyéb helyzetben külön szakmai áttekintés.</span></div>`;
}
