import {currentEvaluation,patientView,isPlanCurrent} from './state.js';
import {gestation,weekLabel} from './engine.js';
import {SOURCES,CHROMOSOMES} from './knowledge.js';
import {LABELS} from './data.js';
import {escapeHtml as e,dateLabel,fullDate,icon} from './ui.js';
import {heroArtwork,gestationRail,carePath,resultCompass,originDiagram,ppvFigure} from './visuals.js';
import {patientMeaning} from './patient.js';
export {patientPanel} from './patient.js';

export const sourceLinks=ids=>`<div class="source-links">${[...new Set(ids)].map(id=>{const s=SOURCES.find(x=>x.id===id);return s?`<a class="source-chip" href="${e(s.url)}" target="_blank" rel="noopener noreferrer">${e(s.authors.split(' · ')[0])} · ${s.year}</a>`:'';}).join('')}</div>`;
const title=(heading,copy)=>`<div class="page-heading"><div><h1>${heading}</h1><p>${copy}</p></div></div>`;
const taskStatus=(t,today)=>t.status==='open'&&t.dueDate<today?'Egyeztetendő, a dátum elmúlt':LABELS.task[t.status];
const stepper=carePath;

export function casePanel(state,c,tab='path'){
  const ev=currentEvaluation(state,c),r=ev.output,active=c.outcome==='ongoing',lastPlan=c.plans.at(-1),shared=patientView(state,c.id);
  const viewDate=active?state.demoDate:(c.closedOn||state.demoDate);
  let body;
  if(tab==='results')body=resultsPanel(c,active);
  else if(tab==='history')body=historyPanel(c);
  else body=`${active?resultCompass(r.stage,r.cpmStatus,c.chromosome):''}${r.gaps.length?`<div class="callout amber">${icon('info')}<div><strong>Pontosításra váró adatok</strong><p>${r.gaps.map(g=>e(g.label)).join(' · ')}</p></div></div>`:''}
    <div class="card card-pad decision-card"><div class="eyebrow">Jelenlegi döntési pont</div><h2>${e(r.stageLabel)}</h2><p class="muted">${e(CHROMOSOMES[c.chromosome]?.description||'Ez a mintaeset külön szakértői áttekintést mutat be.')}</p>${r.steps.map((s,i)=>`<div class="step"><div class="step-number">${i+1}</div><div class="step-content"><h3>${e(s.title)}</h3><div class="meta">${icon('clock')}${e(s.window)}</div><details class="step-explanation"><summary>Indoklás és forrás</summary><p>${e(s.reason)}</p>${sourceLinks(s.sources)}</details></div></div>`).join('')||`<div class="callout teal">${icon('check')}<p>${e(LABELS.outcome[c.outcome])}. A nyitott teendők lezárultak.</p></div>`}
    ${active?`<div class="plan-action"><div><strong>Következő lépés a bemutatóban</strong><p>Tekintsd át, majd fogadd el a bemutatótervet.</p></div><button class="button primary" data-action="approve" data-id="${c.id}">${icon('check')} Terv áttekintése</button></div>`:''}</div>
    ${lastPlan?`<section class="card"><div class="card-header"><h2>Elfogadott bemutatóterv</h2><span class="badge ${isPlanCurrent(state,c,lastPlan)?'teal':'amber'}">${lastPlan.version}. változat${!isPlanCurrent(state,c,lastPlan)?' · Felülvizsgálatra vár':''}</span></div><div class="card-pad"><p>${e(lastPlan.summary)}</p>${lastPlan.overrideReason?`<div class="callout"><div><strong>Orvosi eltérés indoklása a demóban</strong><p>${e(lastPlan.overrideReason)}</p></div></div>`:''}<div class="summary-meta">${icon('calendar')}${fullDate(lastPlan.acceptedOn)} · Szabálycsomag ${e(lastPlan.snapshot.rulesVersion)}</div><div class="inline-actions section-gap">${active&&isPlanCurrent(state,c,lastPlan)?`<button class="button teal" data-action="publish" data-id="${c.id}" data-plan="${lastPlan.id}" ${c.publishedPlanId===lastPlan.id?'disabled':''}>${icon('share')}${c.publishedPlanId===lastPlan.id?'Páciensnézetben megosztva':'Megosztás a páciensnézetben'}</button>`:''}<button class="button" data-action="patient-preview" data-id="${c.id}">${icon('heart')} Páciensnézet</button></div></div></section>`:''}
    <section class="card"><div class="card-header"><h2>Megbeszélt teendők</h2><span class="badge neutral">${c.tasks.filter(t=>t.status==='open').length} nyitott</span></div>${c.tasks.length?`<div class="card-pad task-list">${c.tasks.filter(t=>t.status!=='superseded').map(t=>`<div class="task-row"><div class="task-symbol ${t.status==='done'?'done':''}">${icon(t.status==='done'?'check':'calendar')}</div><div class="task-copy"><strong>${e(t.title)}</strong><span>${dateLabel(t.dueDate)} · ${e(taskStatus(t,state.demoDate))}</span></div>${t.status==='open'&&active?`<button class="button small" data-action="complete-task" data-id="${c.id}" data-task="${t.id}">Teljesítve</button>`:''}</div>`).join('')}</div>`:`<div class="empty compact">${icon('calendar')}<p>A terv elfogadása után itt jelenik meg az egyeztetett teendő.</p></div>`}</section>`;
  return `<a class="back-link" href="#cases">Esetek áttekintése</a><div class="page-heading detail-heading"><div class="case-identity"><span class="chromosome c${c.chromosome}">T${c.chromosome}</span><div><h1>${e(c.label)}</h1><p><span class="mono">${e(c.code)}</span> · ${weekLabel(gestation(c,viewDate))} hét · Mintaeset</p></div></div><div class="heading-actions"><button class="button" data-action="patient-preview" data-id="${c.id}">${icon('user')} Páciensnézet</button>${active?`<button class="button primary" data-action="observation" data-id="${c.id}">${icon('plus')} Lelet hozzáadása</button>`:''}</div></div>
    <div class="journey-label"><span>BETEGÚT-TÉRKÉP</span><small>Aktuális döntési szakasz</small></div>${stepper(r.stage)}<nav class="detail-tabs" aria-label="Eset nézetei">${[['path','Betegút és terv'],['results',`Leletek (${c.observations.length})`],['history','Változatok és napló']].map(([key,label])=>`<a class="${tab===key?'active':''}" href="#case/${c.id}/${key}" ${tab===key?'aria-current="page"':''}>${label}</a>`).join('')}</nav>
    <div class="detail-grid"><div class="stack">${body}</div><aside class="stack"><div class="card card-pad date-card">${gestationRail(active?r.gestationalDays:gestation(c,viewDate),viewDate,active?'A bemutató napján':'A lezárás napján')}</div><div class="card card-pad"><div class="section-title"><h2>Esetadatok</h2>${active?`<button class="icon-button" data-action="dating" data-id="${c.id}" aria-label="Terhességi kor pontosítása">${icon('edit')}</button>`:''}</div><dl class="definition-list"><div><dt>NIPT-jelzés</dt><dd>T${c.chromosome}</dd></div><div><dt>Terhességi kor</dt><dd>${weekLabel(gestation(c,viewDate))} hét</dd></div><div><dt>Terhesség</dt><dd>${c.pregnancyType==='singleton'?'Egyes':c.pregnancyType==='twins'?'Iker':'Nem ismert'}</dd></div><div><dt>Lelet dátuma</dt><dd>${dateLabel(c.niptDate)}</dd></div><div><dt>Vizsgálat</dt><dd>${e(c.assay||'Nem ismert')}</dd></div><div><dt>Lepényi eredet</dt><dd>${e(LABELS.cpm[c.cpmStatus])}</dd></div></dl><div class="mini-note">${icon('info')} A lepényi eredet nincs automatikusan megállapítva a magzati leletből.</div>${active?`<button class="button subtle small section-gap" data-action="context" data-id="${c.id}">Leletadatok pontosítása</button>`:''}</div>
    ${r.timeWindow&&active?`<div class="card card-pad"><div class="eyebrow">Időzítési referencia</div><div class="window-heading">${icon('calendar')}<strong>15+0 hét</strong></div><p class="muted small-copy">${r.timeWindow.open?'A hivatkozott időablak kezdete már elmúlt.':'A hivatkozott időablak kezdete: '+fullDate(r.timeWindow.earliestDate)}</p><p class="small-copy">Ez önmagában nem vizsgálati ajánlás; a választást a kezelőorvos mérlegeli.</p>${sourceLinks(['rcog-8'])}</div>`:''}
    <div class="callout">${icon('shield')}<p><strong>Szakmai egyeztetésre készült.</strong><br>A döntési táblák még nem kaptak klinikai jóváhagyást.</p></div>
    ${active?`<button class="button" data-action="close-case" data-id="${c.id}">${icon('case')} Eset lezárása</button>`:''}
    ${shared.needsReview&&active?'<div class="callout amber"><p>A páciensnézet a korábban megosztott változatot őrzi. Az új lelet után új terv osztható meg.</p></div>':''}</aside></div>`;
}

function resultsPanel(c,active){
  const replaced=new Set(c.observations.map(o=>o.supersedes).filter(Boolean));
  return `<section class="card"><div class="card-header"><h2>Rögzített mintaleletek</h2>${active?`<button class="button small" data-action="observation" data-id="${c.id}">${icon('plus')} Új lelet</button>`:''}</div><div class="card-pad">${c.observations.length?c.observations.slice().reverse().map(o=>`<article class="observation ${replaced.has(o.id)?'replaced':''}"><div class="section-title"><h3>${e(LABELS.kind[o.kind])}</h3><span class="badge ${o.result==='abnormal'?'amber':'neutral'}">${e(LABELS.result[o.result])}</span></div><p class="muted small-copy">${fullDate(o.observedOn)} · ${e(LABELS.method[o.method])}</p><dl class="definition-list"><div><dt>Minta</dt><dd>${e(LABELS.specimen[o.specimen])}</dd></div><div><dt>Célzott eltérés lefedettsége</dt><dd>${o.coversTarget?'Rögzítve':'Nincs megerősítve'}</dd></div></dl>${o.note?`<p class="section-gap small-copy">${e(o.note)}</p>`:''}<div class="inline-actions section-gap">${replaced.has(o.id)?'<span class="badge neutral">Új lelet helyesbítette</span>':active?`<button class="button small" data-action="observation" data-id="${c.id}" data-correct="${o.id}">${icon('edit')} Helyesbítés</button>`:''}</div></article>`).join(''):`<div class="empty compact">${icon('document')}<p>Még nincs megerősítő lelet. A pozitív NIPT szűrési eredményként szerepel.</p></div>`}</div></section>`;
}

function historyPanel(c){return `<section class="card"><div class="card-header"><h2>Elfogadott tervváltozatok</h2><small>Megőrzött összefoglalók</small></div><div class="card-pad">${c.plans.length?c.plans.slice().reverse().map(p=>`<div class="history-row"><div><strong>${p.version}. bemutatóterv</strong><span>${fullDate(p.acceptedOn)} · ${p.id===c.publishedPlanId?'Jelenlegi páciensnézet':(c.publications||[]).some(x=>x.planId===p.id)?'Korábban megosztva':'Elfogadott, nem megosztott'}</span></div><button class="button small" data-action="plan-history" data-id="${c.id}" data-plan="${p.id}">Terv megnyitása</button></div>`).join(''):'<p class="muted">Még nincs elfogadott bemutatóterv.</p>'}</div></section><section class="card"><div class="card-header"><h2>Korábbi értékelések</h2><small>A bemeneti állapot megőrizve</small></div><div class="card-pad">${c.evaluations.slice().reverse().map((v,i)=>`<div class="history-row"><div><strong>${e(v.output.stageLabel)}</strong><span>${dateLabel(v.asOf)} · ${v.revision}. adatváltozat · ${e(v.output.rulesVersion)}</span></div><button class="button small" data-action="replay" data-id="${c.id}" data-eval="${v.id}">Megtekintés</button></div>`).join('')}</div></section><section class="card"><div class="card-header"><h2>Műveleti napló</h2></div><div class="card-pad"><ol class="audit-list">${c.audit.slice().reverse().map(a=>`<li><span class="audit-dot"></span><div><strong>${e(a.action)}</strong><p>${e(a.detail)}</p><small>${dateLabel(a.on)} · ${e(a.actor)}</small></div></li>`).join('')}</ol></div></section>`;}


export function knowledgePanel(){return title('Tudástár','Ábrák, kutatási eredmények és a helyes értelmezéshez szükséges kontextus.')+`<div class="knowledge-top"><section class="knowledge-intro"><span class="hero-kicker">KUTATÁSI HÁTTÉR</span><h2>A bizonyíték<br><em>akkor segít, ha érthető.</em></h2><p>A csoportszintű becslés, a magzati lelet és a személyes gondozás három külön nézőpont.</p><div class="study-scope"><strong>17</strong><span>vizsgálat</span><strong>740 076</strong><span>teszt a PLOS-meta-analízis populációjában</span></div><small>Ez nem azonos a PPV-számítás teljes követésű nevezőjével.</small></section>${ppvFigure()}</div><div class="section-gap">${originDiagram()}</div><div class="section-title section-gap"><div><span class="eyebrow">Kromoszóma szerint</span><h2>Négy kiemelt betegút</h2></div></div><div class="chromosome-overview">${Object.entries(CHROMOSOMES).map(([n,c])=>`<a href="#knowledge/source-${n}" class="chromosome-info"><span class="chromosome c${n}">T${n}</span><div><strong>${e(c.title)}</strong><span>${e(c.tag)}</span></div>${icon('chevron')}</a>`).join('')}</div><div class="section-title section-gap"><h2>Források és értelmezési korlátok</h2><span class="tiny-label">${SOURCES.length} hivatkozás</span></div><div class="source-grid">${SOURCES.map(s=>`<article class="card card-pad source-card" id="${e(s.id)}"><div class="eyebrow">${e(s.type)} · ${s.year}</div><h2>${e(s.title)}</h2><p class="muted">${e(s.authors)}<br>${e(s.scope)}</p><details><summary>Korlátok és ellenőrzési állapot</summary><p>${e(s.limitations)}</p><div class="source-access"><strong>Ellenőrzési állapot</strong><p>${e(s.access)}</p></div></details><a class="button small section-gap" href="${e(s.url)}" target="_blank" rel="noopener noreferrer">${icon('book')} Eredeti forrás</a></article>`).join('')}</div>`;}

export function projectPanel(){return title('A bemutatóról','Közös gondolkodáshoz, a következő fejlesztési döntés előtt.')+
  `<div class="project-intro card card-pad"><span class="badge blue">NIPT Betegút · 0.2</span><div class="project-art">${heroArtwork('patient')}</div><h2>A lelettől az átlátható betegútig</h2><p>Ez a kattintható prototípus azt mutatja meg, hogyan kapcsolódhat össze a leletek értelmezése, az orvosi terv és a páciens tájékoztatása. Az esetek mintaadatokat tartalmaznak, és minden látogató a saját bemutatópéldányát módosítja.</p></div><div class="source-grid section-gap"><section class="card card-pad"><h2>Ami most kipróbálható</h2><ul class="check-list"><li>Hat mintaeset és új bemutatóeset létrehozása.</li><li>Leletbevitel, helyesbítés és dátumpontosítás.</li><li>Forrással indokolt demonstrációs lépések.</li><li>Tervelfogadás és külön páciensnézeti megosztás.</li><li>Teendők, lezárás és visszanézhető változatok.</li><li>Nyomtatható, PDF-ként menthető összefoglaló.</li></ul></section><section class="card card-pad"><h2>A következő szakasz feltételei</h2><p>Az orvosokkal ellenőrzött pilotfejlesztés csak a projektgazda külön, kifejezett jóváhagyásával indulhat, a szakmai vezetővel történt egyeztetés után.</p><ul class="plain-list"><li>Jóváhagyott klinikai döntési táblák.</li><li>Intézményi adatjogok és adatvédelmi vizsgálat.</li><li>Szabályozási besorolás és validációs terv.</li><li>Valódi hitelesítés és betegjogosultságok.</li></ul><span class="badge amber">A pilot nincs elindítva</span></section></div>
  <section class="card card-pad section-gap"><h2>Így érdemes bemutatni</h2><div class="demo-walkthrough"><div><span>01</span><h3>Nyisd meg a T15-es esetet</h3><p>Az UPD külön kérdésként szerepel a magzati lelet mellett.</p><a class="button small" href="#case/demo-15">T15-es mintaeset</a></div><div><span>02</span><h3>Fogadj el egy bemutatótervet</h3><p>A megosztás külön lépés: a páciens csak az egyeztetett változatot látja.</p></div><div><span>03</span><h3>Rögzíts egy új leletet</h3><p>A korábbi terv megmarad, az új adatok felülvizsgálatot jeleznek.</p></div></div></section>
  <section class="card card-pad section-gap"><h2>Adatok és megosztás</h2><p>A bemutató nem kér nevet, e-mail-címet, TAJ-számot vagy leletfeltöltést. Valódi betegadatot a szabad szöveges mezőkbe se írj. A nézetváltás nem bejelentkezés, és nem valós betegjogosultság.</p><p class="muted">A módosítások csak az adott böngészőlapon maradnak meg. A nyilvános linket megnyitó másik látogató az alapmintaesetekkel indul. A kiszolgáló szokásos technikai naplózása ettől külön működhet.</p><div class="inline-actions"><button class="button" data-action="share-demo">${icon('share')} Demólink másolása</button><button class="button" data-action="reset">${icon('refresh')} Saját demó alaphelyzetbe</button></div></section>`;}

export function printMarkup(state,c){
  const {plan:p,needsReview,closed,tasks}=patientView(state,c.id);if(!p)throw Error('Csak megosztott összefoglaló nyomtatható.');
  return `<div class="print-banner"><strong>BEMUTATÓ · MINTAADATOK – BETEGELLÁTÁSRA NEM HASZNÁLHATÓ</strong><br>A dokumentum nem orvosi lelet vagy klinikailag jóváhagyott gondozási terv.</div><h1>NIPT Betegút</h1><p>Páciens-összefoglaló · ${e(p.snapshot.code)} · T${p.snapshot.chromosome}</p><p>${p.version}. megosztott bemutatóváltozat · ${fullDate(p.acceptedOn)}<br>Megosztáskor rögzített terhességi kor: ${weekLabel(p.snapshot.gestationalDays)} hét</p>${needsReview&&!closed?'<p><strong>Ez a korábbi megosztott terv felülvizsgálatra vár.</strong></p>':''}${closed?'<p><strong>A bemutatóeset követése lezárult.</strong></p>':''}<section><h2>Amit eddig tudunk</h2><p>${e(patientMeaning[p.snapshot.stage])}</p><p>${e(p.summary)}</p></section><section><h2>Megbeszélt teendők</h2>${tasks.map(t=>`<p><strong>${e(t.title)}</strong><br>${fullDate(t.dueDate)} · ${e(taskStatus(t,state.demoDate))}</p>`).join('')}</section><section><h2>A tájékoztatás alapja</h2><p>Szabálycsomag: ${e(p.snapshot.rulesVersion)}. A megjelenített információ nem személyre szabott kockázati becslés.</p>${p.snapshot.sources.slice(0,3).map(id=>{const s=SOURCES.find(x=>x.id===id);return s?`<p>${e(s.authors)} (${s.year}) · ${e(s.doi)}</p>`:'';}).join('')}</section><div class="print-footer">NIPT Betegút · 0.2 bemutató · Klinikai jóváhagyás nincs · Nyomtatási demódátum: ${fullDate(state.demoDate)}</div>`;
}
